name = "mattcraig-tech"
workers_dev = true
compatibility_date = "2022-01-20"
compatibility_flags = [ "formdata_parser_supports_files" ] # required
kv_namespaces = [
         { binding = "STATIC", id = "71f84c7a3bc348d6a4749535fa0b850d", preview_id = "59ecddf3e5ed4a85bef94a74f6a06272" }
]
main = "build/worker/shim.mjs"

[vars]
WORKERS_RS_VERSION = "0.0.9"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[rules]]
globs = ["**/*.wasm"]
type  = "CompiledWasm"
