name: Deploy to Testing

on: 
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Checkout, Build, and Publish Test Worker
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Create a testing KV and modify wrangler.toml
        shell: bash
        run: . ./.github/scripts/setup_test_worker.sh
        env:
          PR_NUMBER: ${{ github.event.number }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      - name: Publish test worker
        run: npx wrangler publish
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      - name: Upload Files
        shell: pwsh
        run: ./kv-bulk-upload.ps1
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}