name: Deploy to Testing

on: 
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Checkout, Build, and Publish
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Create a testing KV and modify wrangler.toml
        shell: bash
        run: |
          sed -i "s/mattcraig-tech/mattcraig-tech-pr${PR_NUMBER}/" wrangler.toml
          NAMESPACE=$(npx wrangler kv:namespace create STATIC | sed ':again;$!N;$!b again; s/.*\({[^}]*}\).*/\1/g')
          echo $NAMESPACE
          sed -i "s/{[^}]*}/${NAMESPACE}/g" wrangler.toml
          cat wrangler.toml
        env:
          PR_NUMBER: ${{ github.event.number }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      - name: Publish test worker
        run: npx wrangler publish
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      - name: Upload Files
        shell: pwsh
        run: ./kv-bulk-upload.ps1
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}